### ISSUE TITLE
BUG PHP 8 - #125670: "Unable to confirm any available moves."

### ISSUE THREAD

**Issue by joesimpson** [Syarwin/bga-coalbaron#2]
LOGS de prod d'un joueur de Phoenix 
```
[30-May-2024 08:44:59 America/Phoenix] PHP Fatal error:  Uncaught Error: Non-static method APP_DbObject::getCollectionFromDB() cannot be called statically in /var/tournoi/release/games/coalbaron/240529-0912/modules/php/Managers/Meeples.php:155
#0 /var/tournoi/release/games/coalbaron/240529-0912/modules/php/States/NewShiftTrait.php(25): COAL\Managers\Meeples::getPlayerMajorityInFactory()
#3 /var/tournoi/release/games/coalbaron/240529-0912/modules/php/States/EndShiftTrait.php(20): Gamestate->nextState()
#6 /var/tournoi/release/games/coalbaron/240529-0912/modules/php/States/NextPlayerTrait.php(23): Gamestate->nextState()
#9 /var/tournoi/release/games/coalbaron/240529-0912/modules/php/States/ConfirmUndoTrait.php(52): Gamestate->nextState()
#10 /var/tournoi/release/games/coalbaron/240529-0912/coalbaron.action.php(145): CoalBaron->actConfirmTurn()
  thrown in /var/tournoi/release/games/coalbaron/240529-0912/modules/php/Managers/Meeples.php on line 155
```

**Comment by joesimpson** [comment]
Fixed in last version (240531-1107)
